# Generated by Django 6.0.3 on 2026-05-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0004_alter_resume_created_at_alter_resume_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('viewed', 'Просмотрен'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус отклика')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='resumes.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
            },
        ),
    ]
