# Generated by Django 6.0.3 on 2026-05-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
        ('companies', '0001_initial'),
        ('resumes', '0004_alter_resume_created_at_alter_resume_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус приглашения')),
                ('message', models.TextField(blank=True, verbose_name='Текст приглашения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Приглашен')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='resumes.resume', verbose_name='Резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='companies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('vacancy', 'resume'), name='unique_invitation_per_vacancy_resume')],
            },
        ),
    ]
