# Generated by Django 6.0.3 on 2026-05-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Москва', max_length=50, verbose_name='Город'),
        ),
    ]
