# Generated by Django 6.0.3 on 2026-05-01 15:06

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', validators=[core.utils.validate_image_size], verbose_name='Логотип сайта')),
                ('main_banner', models.ImageField(upload_to='', validators=[core.utils.validate_image_size], verbose_name='Hero изображение')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
