# Generated by Django 6.0.3 on 2026-05-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_favoritevacancy'),
        ('resumes', '0004_alter_resume_created_at_alter_resume_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_views', to='companies.company', verbose_name='Компания')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_views', to='resumes.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Просмотр резюме',
                'verbose_name_plural': 'Просмотры резюме',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('company', 'resume', 'date'), name='unique_resume_view_per_date')],
            },
        ),
    ]
