# Generated by Django 6.0.3 on 2026-05-01 12:28

import companies.utils
import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professions', '0003_alter_categoryprofession_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('website', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('logo', models.ImageField(blank=True, upload_to=companies.utils.logo_upload_path, validators=[core.utils.validate_image_size], verbose_name='Логотип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Общее описание')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('salary_type', models.CharField(choices=[('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц'), ('twice_monthly', '2 раза в месяц'), ('daily', 'Ежедневно'), ('hourly', 'По часам'), ('negotiable', 'Договорная')], max_length=20, verbose_name='Тип зарплаты')),
                ('experience_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Минимальный опыт')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная'), ('part_time', 'Частичная'), ('internship', 'Стажировка'), ('contract', 'Контракт'), ('remote', 'Удалённая работа')], default='full_time', max_length=20, verbose_name='Тип занятости')),
                ('schedule', models.CharField(choices=[('day', 'Дневные смены'), ('night', 'Ночные смены'), ('flexible', 'Гибкий график'), ('shift', 'Сменный график'), ('remote', 'Удалённо')], default='day', max_length=20, verbose_name='График работы')),
                ('working_hours', models.CharField(blank=True, max_length=20, verbose_name='Рабочие часы')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='companies.company', verbose_name='Компания')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='professions.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='companies.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о компании',
                'verbose_name_plural': 'Отзывы о компаниях',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_feedback_per_user_company')],
            },
        ),
    ]
