# Generated by Django 6.0.3 on 2026-05-01 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to='companies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Избранная вакансия',
                'verbose_name_plural': 'Избранные вакансии',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'vacancy'), name='unique_favorite_vacancy_per_user')],
            },
        ),
    ]
