# Generated by Django 6.0.3 on 2026-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_favoritevacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='street',
            field=models.CharField(blank=True, max_length=50, verbose_name='Улица'),
        ),
    ]
