# Generated by Django 6.0.3 on 2026-05-06 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_hiddenvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcompany',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='companies.vacancy', verbose_name='Вакансия'),
        ),
    ]
