# Generated by Django 6.0.3 on 2026-05-07 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_feedbackcompany_vacancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Скрыто')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_companies', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Скрытая компания',
                'verbose_name_plural': 'Скрытые компании',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_hidden_company_per_user')],
            },
        ),
    ]
