# Generated by Django 6.0.3 on 2026-04-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_feedbackcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='experience',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Минимальный опыт'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальный опыт'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная зарплата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
    ]
