# Generated by Django 6.0.3 on 2026-05-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='companies.vacancy', verbose_name='Вакансия'),
        ),
    ]
