# Generated by Django 6.0.3 on 2026-05-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_alter_profession_category_alter_profession_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryprofession',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryprofession',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professions', to='professions.categoryprofession', verbose_name='Категория профессии'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание профессии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название профессии'),
        ),
    ]
